spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.6.128
    port: 5672
    username: admin
    password: admin 
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

#zuul会默认配置下面的配置 会通过注册中心获取服务 可以不自行配置
zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
  retryable: true
  
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream